### ISSUE TITLE
[Idea/Feature Request] Support deprecated/removed functionality

### ISSUE THREAD

**Issue by GenieTim** [rosswintle/can-i-php#10]
It would be quite handy to be able to also query for functions that have been removed at some point (e.g. `get_magic_quotes_gpc`) and see what PHP version is the latest to support that function.

**Comment by rosswintle** [comment]
It was already supported in the data. I've made a tweak to the display code and README and added `get_magic_quotes_gpc` as an example: http://caniphp.com/?s=get_magic_quotes_gpc

**Comment by rosswintle** [comment]
BUT... thanks for the suggestion - I really appreciate every idea! 🙌

**Comment by GenieTim** [comment]
Oh, sorry, that must have been carelessness on my side. Thank you very much!
I will try to make a PR with some more examples some time.

**Comment by rosswintle** [comment]
You're good. It wasn't obvious because I hadn't added any deprecations yet.

PRs would be appreciated - thank you!
