### ISSUE TITLE
Functions like array_column are missing

### ISSUE THREAD

**Issue by dsentker** [rosswintle/can-i-php#21]
It would be great to learn about the support for functions like `array_column()`.

**Comment by rosswintle** [comment]
Thanks.

Looks like this was added in PHP 5.5. I wasn't planning going back that far, but is that useful for you to know about?

Can you say what other functions would be good to know about? I'm not going to turn this into a comprehensive list of ALL internal PHP functions.

**Comment by dsentker** [comment]
Oh, i was not aware that array_column is so old. Maybe i've chosen the wrong example. How about all functions added since 7.x? `array_key_first` / `array_key_last` would be a nice start.

**Comment by rosswintle** [comment]
Yes, that would be great. Do you think you could add these and submit a PR? There are instructions in the README.

I can add it if not.

The plan is that, eventually, I'll sit down with the migration guide for each version and ensure it's got all the additions and removals in. But I need to find time to do it.

**Comment by rosswintle** [comment]
Thanks for this suggestions. I've added these functions.
